### PR TITLE
Modernised Document Hub UI

### LINKED ISSUE #183: Modernise the Document Hub UI
Since some parts of the SubEthaEdit UI might look a bit out of place on modern macOS, I'd like to work a bit on that.

Here's a quick first mockup for an updated Document Hub. Apart from the new chrome, I tried to vertically align the text labels, removed the gradient backgrounds, and moved the New, Open and Connect buttons to the toolbar.

 Before I start working on it: all feedback welcome. 

Screenshot 2020-12-01 at 01 13 19

### PR DESCRIPTION
**Pull request by jncn**
Here's my first attempt at modernising the Document Hub UI 🤞🏼

As you can see, there are not too many compromises on the proposed design in #183. Although not identical, I think it turns out okay on older systems. This screenshot is from 10.14 on VMWare (hence the lack of translucency).

I've opted in to `NSTableViewStyleInset` on macOS 11. This adds a bit more space around the table view compared to the mockup. It also renders the right click highlight much nicer.

Document Hub

Here's a summary of less obvious things which have changed:
- A regression over the previous implementation is that right clicking New, doesn't present a menu with Modes. This is not supported on `NSToolbarItem` and I haven't found a good work around for it yet. I like Xcode's Build button behaviour, where you have to long press to reveal the menu. Or maybe we have to keep it simple and use a pull down instead of a regular button?
- The hover effect now also works when the Document Hub is not the active window. This is more inline with what Finder and other apps do (try the toolbar on Big Sur).
- The hover effect now only works for documents. I removed it from the Recent Documents and Show More items, as it felt a little out of place there.
- `SEENetworkBrowserGroupTableRowView` is not sticky anymore for now. If that's a must, I can put more effort to work around the default style. The OS adds bottom separators etc.
- The Disconnect button is now an eject icon instead of an ×, like in Finder.
- Truncated document names now show a tooltip with their full name on hover.
- I used existing German localisations where possible for the toolbar, but translated the tooltips myself. Please verify 😉 

Some thoughts:
- Wouldn't it be nicer if Show More would load the missing recent documents in the table view, instead of a menu?
- A Show in Finder option would be convenient when right clicking a (local) file.
- Shouldn't Connect to Host be present in the Main Menu too?

Feel free to comment, make changes, etc. All input welcome, especially ideas on fixing the regressions.

P.S. This PR also includes #182, I'm a bit clumsy with GIT sometimes.

### CODE REVIEW

**Comment by monkeydom** [comment]
Looks good generally speaking. Will have a closer look and probably push some commits with my changes on it. Thanks for your initiative. Factored out the open url change and remerged.

**Comment by monkeydom** [comment]
Some opinions to your thoughts:

> Wouldn't it be nicer if Show More would load the missing recent documents in the table view, instead of a menu?

I think the menu is fine there for quick access. A super long table view doesn't really help. If you want you could do another disclosure triangle and put it inline, but I do think it should be indented.

> A Show in Finder option would be convenient when right clicking a (local) file.

Actually cmd-click should do that imho as it is in spotlight. somehow though that isn't the case (anymore?). I think we should readd this, however, the recent document menu is populated by the system, don't know if there currently is an easy way to do this.

> Shouldn't Connect to Host be present in the Main Menu too?

Yes it should. And I could swear it was on shift-cmd-k at one point in time. But since this is the inverse of finder (where cmd-k is the connect dialog, and cmd-shift-k shows the network panel I'm unsure what the best solution is.)

**Comment by monkeydom** [comment]
Pasted_Image_12_3_20__11_41
Truncate center is probably the better choice here. I also would prefer a minimum window width that ensures the toolbar, and not allowing customization of that toolbar.

**Comment by monkeydom** [comment]
Interesting. The SF Symbols still report a warning, although you put them into the asset catalog as well. Would like to see that go away. Otherwise the change looks good to me. Let me know what you think.

**Review by monkeydom — APPROVED** [review]

**Comment by jncn** [comment]
Looking good, thanks for the additions! I'll keep the code style habits in mind for the next round.

The customise toolbar was enabled so users could choose to show labels, but that's indeed not really needed. I'm a bit old-fashioned in that regard 😉 

As for the SF Symbols: this is a bug in Xcode. The moment I open the XIB again, the warnings usually go away. Unfortunately they return after some time. Unclear why or when.

I'll add the Show in Finder (and cmd+click) and Connect to Host in Main Menu tonight.

**Comment by jncn** [comment]
As discussed: 
- Show in Finder is added to the Main Menu
- Show in Finder is added to the Context Menu in the Document Hub 
- Cmd+Click on a file in the Document Hub also triggers Show in Finder
- Connect to Host is added (again?) to the Main Menu (mapped to ⇧⌘K, which was set as alternate for Document Hub) 

Furthermore, I have some questions about `triggerItemDoubleClickAction:` in `SEEDocumentListWindowController`:
This method is now identical to `triggerItemClickAction:`. Not setting it to `tableView.doubleAction` doesn't make any difference. It looks like it's a left over from when double clicking was possible (as a user pref?), depending on the value of `SEEDocumentListOpenDocumentsWithSingleClick`. Since this is not implemented anymore, maybe this is a good opportunity to clean this up together with its related implementations? e.g. Selecting multiple files in `tableView:shouldSelectRow:`.

With this solved, I think we're almost there for now. Any other suggestions?

**Comment by monkeydom** [comment]
Thanks, I'm a little bit slow here currently, hopefully get to review your changes tomorrow. Might want to release a 5.1.6 early because of the big sur print bug.

**Comment by jncn** [comment]
No worries, take your time! Maybe it would make sense to bundle all of the UI stuff in a 5.2 update instead?

**Comment by monkeydom** [comment]
Generally speaking yes. But I do think the Document hub is so jarring, to actually have this neat cleanup as it is ready to go is good. Also in a more general sense I'd like to just release work when it is done vs. really packing up huge releases.

**Comment by monkeydom** [comment]
Yes, I do think the `SEEDocumentListOpenDocumentsWithSingleClick` is just a leftover of days where we were undecided. Will clean that up now. Thanks for the great work!

**Comment by jncn** [comment]
Very cool, thanks. Happy to contribute!

**Pull request merged**
