### PR TITLE
Preferences UI

### PR DESCRIPTION
**Pull request by jncn**
Over the weekend I updated Preferences to better follow current OS conventions, and have improved legibility. This is a work in progress, as I think a few conceptual simplifications would make sense too.

General improvements:
- All panels now have the same width, preventing the horizontal animation.
- Most controls now have the regular size, which is the de facto standard for preference windows.
- Preferences are not longer laid out as boxes (within boxes), but grouped per title. Just like most other apps.
- Aligned the SF Symbol toolbar icons with system apps, e.g. `gearshape` for General and `gearshape.2` for Advanced.

Specific improvements:
- Collaboration has a totally new lay out, with Disable Networking renamed to Enable Collaboration (plus updated logic behind the scenes).
- The command line tool script now had a copy button. An install button would be even better, but I guess that's not possible with Sandboxing?
- Styles no longer has radio buttons to choose the Default style for a specific mode. With a specific mode selected, that option is now the first item in the Style dropdown.
- Little detail on Editing: labels are now also dimmed when Use Default is checked on a specific mode.

Open questions:
- Although it's well implemented, I'm wondering if it's really useful to be able to override Editing and Style preferences per Mode? I couldn't find any other apps doing this, and personally never felt the need to do so. Removing this feature would simplify those settings a lot.
- Editing is quite big right now, I think it wouldn't hurt to use a Segmented Control here for View, Edit and File.

To-do's:
- Implement German localisation. Would it be okay to switch to Strings, if it doesn't brake the lay out? Maintaining multiple XIB's is quite something.

Thoughts and comments welcome!

### CODE REVIEW

**Comment by jncn** [comment]
Of course #187 sneaked in here again 🤦🏼‍♂️ My apologies...
Edit: fixed the merge conflict this caused.

**Comment by monkeydom** [comment]
I'll try to have a look at it soon. Quick answer to one of your questions:

> * Although it's well implemented, I'm wondering if it's really useful to be able to override Editing and Style preferences per Mode? I couldn't find any other apps doing this, and personally never felt the need to do so. Removing this feature would simplify those settings a lot.

Yeah - but that is not an area we can compromise. It is very common for people working in multiple langauges to have different editing settings there to work with their projects. I mean we could enhance everything by also supporting corresponding confiruation files (there are some standards), but the tabs v. spaces and widht settings alone are very much per mode and language

**Comment by monkeydom** [comment]
Yeah - converting to strings files would probably be okay if the layout allows for it. previously it didn't very much.

Also note that the excessive use of Controller-bindings might also be very brittle, so touching these xibs is riddled with much anxiety.

**Comment by jncn** [comment]
With the localisations done, apart from a few German strings, I think this one's ready for review too now.
I've marked the missing strings with `LOCALISATION MISSING`. 

 I quite like how it's turned out in general, but of course comments and more ideas for improvement welcome!

**Comment by monkeydom** [comment]
Cool, hope to have a look soon. Btw: if you are interested in generating better App Store screenshots for SubEthaEdit too, that would be appreciated. My time is usually cut quite short for that, so the German and English App Store screenshots are somewhat mediocre.

**Comment by jncn** [comment]
With pleasure! I'll send some proposals tonight.

**Comment by monkeydom** [comment]
Pasted_Image_13_12_2020__15_22
Pasted_Image_13_12_2020__15_23
Pasted_Image_13_12_2020__15_23
Pasted_Image_13_12_2020__15_24
Pasted_Image_13_12_2020__15_24
Pasted_Image_13_12_2020__15_25

Providing before/after screenshots for reference. First impression is very nice.

**Comment by monkeydom** [comment]
Overall looks very nice and much cleaner now. Thanks for the work.

However, one immediate nitpick that need to be addressed:

- Both styles and Trigger panes need to be allowed to be resizable, maybe make triggers even have a min size that already accommodates at least all built in ones since you increased the overall sizes anyways. (pet peeve of mine, I hate mac apps that show stuff in non resizable parts although the screen estate would allow it. E.g. App Store and a lot of other apps)

**Comment by jncn** [comment]
Good point, and indeed setting a min value would be sufficient. Are you talking about both horizontal and vertical? Or just vertical?

**Comment by monkeydom** [comment]
Just vertical is fine for me. Not at all is feeling hurtful. Note that I merged in the changes on develop for the find and replace UI, please double check the project because I had to do manual conflict resolving on the project file.

**Review by monkeydom — APPROVED** [review]
Sweet. Looks good to me. Made slight adjustments to some metrics.

**Pull request merged**
