### PR TITLE
Use native tabs

### PR DESCRIPTION
**Pull request by fourplusone**
This PR removes PSMTabBarControl in favor of AppKit's native tabbing (relating to #14 #43). There are a few open issues which needs to be resolved before merging

- [x] Reenable State Restoration
- [x] The line number ribbon is not visible in some cases
- [x] Fix window resizing for Split View
- [x] Resolve all introduced `TODO`s
- [x] Update Deployment Target to 10.12 (See #75)
- [x] functionality: next/previous tab needs to put the first responder in the text view
- [x] functionality: tab titles should be reduced to the filename only (currently if you show path components they are shown in the tab titles which is overkill)
- [x] functionality: ctrl-1 was a keyboard shortcut to show a menu with all open files, this is now defunct. needs to be reinstated

Points that can be addressed in separate issues after committing the initial work:
- [ ] Remove all unused functionality from PlainTextWindowController
- [ ] Refactor and Rename the `PlainTextWindowControllerTabContext`
- [ ]  optics: at least in dark mode using the native tabbing needs work in adding lines on top of the window. Also the top status bar looks slightly off now, probably best done in a separate issue
- [ ]  while only a side effect: I don't think merge all windows should merge in multiple views of the same document, as the only reason for having them is to get some side by side action happening
- [ ]  Personally I did like the title of "Always Show Tab Bar" better than "Show Tab Bar" as you never can hide the tab bar when there are tabs in a window anyways.

However I decided to share my initial work to open up the discussion about the implementation. Comments on this are highly welcome :)

### CODE REVIEW

**Comment by monkeydom** [comment]
❤️  Nice to see some movement here! Try to look through it soon. Depending on the state of this maybe we should add a feature-branch on the main repo instead of going to develop immediately?

**Comment by monkeydom** [comment]
Looks good so far (pulled it in this repo too for messing with it). Small issues that need addressing:

- [ ] optics: at least in dark mode using the native tabbing needs work in adding lines on top of the window. Also the top status bar looks slightly off now
- [ ] functionality: next/previous tab needs to put the first responder in the text view
- [ ] functionality: tab titles should be reduced to the filename only (currently if you show path components they are shown in the tab titles which is overkill)
- [ ] functionality: ctrl-1 was a keyboard shortcut to show a menu with all open files, this is now defunct. needs to be reinstated
- [ ] while only a side effect: I don't think merge all windows should merge in multiple views of the same document, as the only reason for having them is to get some side by side action happening
- [ ] Personally I did like the title of "Always Show Tab Bar" better than "Show Tab Bar" as you never can hide the tab bar when there are tabs in a window anyways.

**Comment by fourplusone** [comment]
I think this one is ready for merge. However, #74 should be merged (or closed) before

**Comment by monkeydom** [comment]
Sweet. Will try to have a look tomorrow.

**Comment by monkeydom** [comment]
Looks like we need to merge in develop again, before we can squash and merge. I'l leave that to you, if that is ok.

**Pull request merged**
